spin_manifest_version = "1"
authors = ["Adam Reese <adam@reese.io>"]
description = "A sentiment analysis API that demonstrates using LLM inference and KV stores together"
name = "sentiment-analysis"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "sentiment-analysis"
source = "main.wasm"
allowed_http_hosts = []
key_value_stores = ["default"]
ai_models = ["llama2-chat"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
