[package]
name = "http-rust-hello"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
# Useful crate to handle errors.
anyhow = "1"
# Crate to simplify working with bytes.
bytes = "1"
# General-purpose crate with common HTTP types.
http = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"

# The Spin SDK.
spin-sdk = { path = "../../spin/sdk/rust" }

[workspace]
